# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iofogctl < Formula
  desc "CLI for iofog"
  homepage "https://github.com/eclipse-iofog/iofogctl"
  version "3.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.8/iofogctl_3.0.8_macos_arm64.tar.gz"
      sha256 "3529276ff2cdc21b44b0f0e3cefb93c6172552fd5c7441a6393701747bb7d17f"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.8/iofogctl_3.0.8_macos_amd64.tar.gz"
      sha256 "b92247bab59121f88d86f91fcf3fb123c59767f1887bd659d854d4198f491ec8"

      def install
        bin.install "iofogctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.8/iofogctl_3.0.8_amd64.tar.gz"
      sha256 "1f171295ed835d1e90870acdc996cd6efe0cbd7b9615fc7da008c87d9ec0af30"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.8/iofogctl_3.0.8_armv6.tar.gz"
      sha256 "c17700cab4ffaf4e6ee9a203219dcf69290c2d200f476211750507c62bfa08f9"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.8/iofogctl_3.0.8_arm64.tar.gz"
      sha256 "60f99584f53f179cb248aa6ba381f4e36175fb957b7b9a809aab9c2a32070610"

      def install
        bin.install "iofogctl"
      end
    end
  end

  test do
    system "#{bin}/iofogctl version"
  end
end
